# exception_assert
Assert that throws a logic_error to give application a chance to handle
